/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container": "#edeeef",
        "surface-tint": "#3e5e95",
        "surface": "#f8f9fa",
        "on-primary-fixed-variant": "#24467c",
        "inverse-primary": "#abc7ff",
        "background": "#f8f9fa",
        "secondary": "#29695b",
        "surface-dim": "#d9dadb",
        "tertiary": "#151c00",
        "on-primary-container": "#7796d1",
        "on-primary-fixed": "#001b3f",
        "surface-variant": "#e1e3e4",
        "inverse-surface": "#2e3132",
        "surface-container-low": "#f3f4f5",
        "tertiary-fixed-dim": "#b0d500",
        "surface-bright": "#f8f9fa",
        "tertiary-container": "#283200",
        "on-secondary-container": "#2e6d5f",
        "inverse-on-surface": "#f0f1f2",
        "surface-container-highest": "#e1e3e4",
        "on-tertiary-fixed": "#171e00",
        "on-background": "#191c1d",
        "primary": "#00193c",
        "on-primary": "#ffffff",
        "outline-variant": "#c4c6d1",
        "secondary-fixed": "#afefdd",
        "surface-container-high": "#e7e8e9",
        "on-tertiary-container": "#85a000",
        "secondary-container": "#acedda",
        "primary-fixed-dim": "#abc7ff",
        "tertiary-fixed": "#caf300",
        "outline": "#747781",
        "on-surface-variant": "#43474f",
        "primary-fixed": "#d7e2ff",
        "on-secondary-fixed-variant": "#065043",
        "primary-container": "#002d62",
        "secondary-fixed-dim": "#94d3c1",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "on-secondary": "#ffffff",
        "on-error-container": "#93000a",
        "on-tertiary-fixed-variant": "#3e4c00",
        "on-secondary-fixed": "#00201a",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#191c1d",
        "on-tertiary": "#ffffff"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
    },
  },
  plugins: [],
}
